**Matrix Multiplication We will use tf.matmulO method Rules**
1. Inner dimensions must match (m,n)@(n.p) for e.g.
*   (5,7)@(8,9) It will not work because n are different
*   (5,8)@(8,9) It will work because inner dimension is same
2. The result matrix has the shape of outer dimension, means A (m,n) B (n,p) So result has (m,p) e.g (4,7)@(7,5)-> (4,5)






In [1]:
import tensorflow as tf
import numpy as np

In [8]:
tensor_A=tf.constant([[1,2],[3,4],[4,5]],dtype=tf.int32)
tensor_B=tf.constant([[5,6],[7,8]],dtype=tf.int32)
print('Shape of A',tensor_A.shape)
print('Shape of B',tensor_B.shape)

Shape of A (3, 2)
Shape of B (2, 2)


In [9]:
tensor_C=tf.matmul(tensor_A,tensor_B)
print(tensor_C)
print('Shape of tensor_C:',tensor_C.shape)

tf.Tensor(
[[19 22]
 [43 50]
 [55 64]], shape=(3, 2), dtype=int32)
Shape of tensor_C: (3, 2)


In [ ]:
X=tf.constant([[1.,0.,-1.],
                [2.,3.,1.]],
                 dtype=tf.float32)
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  0., -1.],
       [ 2.,  3.,  1.]], dtype=float32)>

In [ ]:
Y=tf.constant([
    [4.],
    [5.],
    [6.]
],dtype=tf.float32)
Y

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>

In [ ]:
print("X-Shape",X.shape)
print("Y-Shape",Y.shape)

X-Shape (2, 3)
Y-Shape (3, 1)


In [ ]:
Z=tf.matmul(X,Y)
Z

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-2.],
       [29.]], dtype=float32)>

In [ ]:
print(f'X-Shape:{X.shape},Y-shape:{Y.shape},Z-shape: {Z.shape}')
print(X.numpy())
print(Y.numpy())
print(Z.numpy())

X-Shape:(2, 3),Y-shape:(3, 1),Z-shape: (2, 1)
[[ 1.  0. -1.]
 [ 2.  3.  1.]]
[[4.]
 [5.]
 [6.]]
[[-2.]
 [29.]]


Transpose: Transpose swaps axes. For 2D matrix shape(m.n) become(n,m) after transpose

In [10]:
tensor_one=tf.constant([
    [[1,2],[2,3]],
    [[4,5],[6,7]]
],dtype=tf.int32)
tensor_one

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)>

In [ ]:
tensor_one_transpose=tf.transpose(tensor_one)
print(tensor_one_transpose)
print('Shape of tensor_one_transpose',tensor_one_transpose.shape)

tf.Tensor(
[[[1 4]
  [2 6]]

 [[2 5]
  [3 7]]], shape=(2, 2, 2), dtype=int32)
Shape of tensor_one_transpose (2, 2, 2)


In [11]:
# 3D Transpose with Explicit axis Perrmutation
tensor_two=tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
],dtype=tf.int32)
print(tensor_two)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [12]:
# Swap First and Last axis (0,1,2)->(0,2,1)
t2_transpose=tf.transpose(tensor_two,perm=[0,2,1])
print(t2_transpose)
print('\nShape of t2_transpose',t2_transpose.shape)
print('\nShape of tensor_twi',tensor_two.shape)

tf.Tensor(
[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]], shape=(2, 2, 2), dtype=int32)

Shape of t2_transpose (2, 2, 2)

Shape of tensor_twi (2, 2, 2)


In [ ]:
# Reshape
#tf.reshape(tensor, new_shape)
# Change the shape without Changing the Data
# Rule: The Total Number of Elements must Stay The Same

In [13]:
tensor=tf.constant([
    [1,2,3],
    [4,5,6]
],dtype=tf.int32)
print(tensor)
print('\nShape of Tensor',tensor.shape)
print('\nNumber of Elements are:',tf.size(tensor).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Shape of Tensor (2, 3)

Number of Elements are: 6


In [14]:
tensor_r1=tf.reshape(tensor,shape=(3,2))
print(tensor_r1)
print('\nShape of tensor_r1',tensor_r1.shape)
print('\nNumber of elements are:',tf.size(tensor_r1).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Shape of tensor_r1 (3, 2)

Number of elements are: 6


In [15]:
tensor_r1=tf.reshape(tensor,shape=(1,6))
print(tensor_r1)
print('\nShape of tensor_r1',tensor_r1.shape)
print('\nNumber of elements are:',tf.size(tensor_r1).numpy())

tf.Tensor([[1 2 3 4 5 6]], shape=(1, 6), dtype=int32)

Shape of tensor_r1 (1, 6)

Number of elements are: 6


In [16]:
# Infer Dimension
tensor_r4=tf.reshape(tensor,shape=(-1,2))
print(tensor_r4)
print('\nShape of tensor_r4',tensor_r4.shape)
print('\nNumber of elements are:',tf.size(tensor_r4).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Shape of tensor_r4 (3, 2)

Number of elements are: 6


In [ ]:
# Task: Reshape(2,6)->(3,4)and(1,12)
tensor_given=tf.constant([[1,2,3,4,5,6],
                          [7,8,9,10,11,12]],dtype=tf.int32
                         )

In [ ]:
tensor_r10=tf.reshape(tensor_given,shape=(3,4))
print(tensor_r10)
print("Shape of tensor_r10 :",tensor_r10.shape)
print("Number of elements are :",tf.size(tensor_r10).numpy())

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
Shape of tensor_r10 : (3, 4)
Number of elements are : 12


In [ ]:
tensor_r11=tf.reshape(tensor_given,shape=(1,12))
print(tensor_r11)
print("Shape of tensor_r11 :",tensor_r11.shape)
print("Number of elements are :",tf.size(tensor_r11).numpy())

tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10 11 12]], shape=(1, 12), dtype=int32)
Shape of tensor_r11 : (1, 12)
Number of elements are : 12
