##### TensorFlow Basics

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
print(tf.__version__)

2.19.0


In [ ]:
# Creating Tensor with Constant
# The Function used: model=tf.constant(9)    #model is variable
# Example: scalar=tf.constant(9)
#         scalar
#         scalar.ndim

In [ ]:
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
scalar.ndim

0

In [ ]:
matrix=tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
sec_matrix=tf.constant([[5,7],
                        [3,8],
                        [3,9],
                        [4,2],
                        [8,6]])

In [ ]:
sec_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [ ]:
sec_matrix.ndim

2

In [ ]:
third_mat=([[[1,2,3],
             [2,4,5]],
             [[7,9,3],
             [10,4,5]],
             [[11,2,3],
             [2,4,15]]])
third_mat

[[[1, 2, 3], [2, 4, 5]], [[7, 9, 3], [10, 4, 5]], [[11, 2, 3], [2, 4, 15]]]

In [ ]:
sec_matrix=tf.constant([[5.6,7.3],[3.45,8.25],
                        [3.11,9.23],
                        [4.34,2.34],
                        [8.4,2.3]
                        ])
sec_matrix

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[5.6 , 7.3 ],
       [3.45, 8.25],
       [3.11, 9.23],
       [4.34, 2.34],
       [8.4 , 2.3 ]], dtype=float32)>

In [ ]:
# Singe Num means Scalar
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
# Num with Direction
vector=tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [ ]:
# 2-D Array of Numbers
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Tensor: An n-Dimensional Array of Numbers (n=0,n=1,n=2......)
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [ ]:
# Find the **Shape**, **Rank**, **Dimension** and **Size** of The

#SCALAR (Single Number)
print("----Scalar Information----")
print("Shape: \t",scalar.set_shape)
print("\nDimension: \t",scalar.ndim)
print("\nRank: \t",tf.rank(scalar).numpy())
print("\nSize: \t",tf.size(scalar))

----Scalar Information----
Shape: 	 <bound method _EagerTensorBase.set_shape of <tf.Tensor: shape=(), dtype=int32, numpy=5>>

Dimension: 	 0

Rank: 	 0

Size: 	 tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
#VECTOR (1D Array)
print("----Vector Information----")
print("Shape: \t",vector.shape)
print("\nDimension: \t",vector.ndim)
print("\nRank: \t",tf.rank(vector).numpy())
print("\nSize: \t",tf.size(vector))

----Vector Information----
Shape: 	 (4,)

Dimension: 	 1

Rank: 	 1

Size: 	 tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
#MATRIX (2D Array)
print("----Matrix Information----")
print("Shape: \t",matrix.shape)
print("\nDimension: \t",matrix.ndim)
print("\nRank: \t",tf.rank(matrix).numpy())
print("\nSize: \t",tf.size(matrix))

----Matrix Information----
Shape: 	 (2, 2)

Dimension: 	 2

Rank: 	 2

Size: 	 tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
#TENSOR (3D Array)
print("----Tensor Information----")
print("Shape: \t",tensor.shape)
print("\nDimension: \t",tensor.ndim)
print("\nRank: \t",tf.rank(tensor).numpy())
print("\nSize: \t",tf.size(tensor))

----Tensor Information----
Shape: 	 (2, 2, 2)

Dimension: 	 3

Rank: 	 3

Size: 	 tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
# Create Tensor using Variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [ ]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [ ]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(12)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
# Random Tensors
random_tensors=tf.random.Generator.from_seed(42)
random_tensors=random_tensors.normal(shape=(3,2))
random_tensors

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_tensors_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensors_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.9490979 , 0.86971796, 0.36976767, ..., 0.54818547, 0.42414367,
        0.6619824 ],
       [0.44805133, 0.17835176, 0.08538389, ..., 0.9546443 , 0.3327061 ,
        0.6320307 ],
       [0.95357275, 0.60418046, 0.17366886, ..., 0.05308151, 0.20592177,
        0.5392175 ],
       ...,
       [0.7578057 , 0.15120125, 0.51725733, ..., 0.14314616, 0.17266536,
        0.41776717],
       [0.21490324, 0.01059031, 0.6132126 , ..., 0.7169168 , 0.87709916,
        0.5789634 ],
       [0.72058034, 0.93597126, 0.92605567, ..., 0.36642408, 0.05601823,
        0.8483691 ]], dtype=float32)>

In [ ]:
random_tensors_3=tf.random.Generator.from_seed(42)
random_tensors_3=random_tensors_3.normal(shape=(3,2))

random_tensors_4=tf.random.Generator.from_seed(42)
random_tensors_4=random_tensors_4.normal(shape=(3,2))
random_tensors_3,random_tensors_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [ ]:
random_tensors_3=tf.random.Generator.from_seed(42)
random_tensors_3=random_tensors_3.normal(shape=(3,2))

random_tensors_4=tf.random.Generator.from_seed(15)
random_tensors_4=random_tensors_4.normal(shape=(3,2))
random_tensors_3,random_tensors_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

In [ ]:
# Creating Tensors using Zeros

# Normal Interger
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [ ]:
# With Decimals
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [ ]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [ ]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [ ]:
print("----Tensor Information----")
print("Shape: \t",tensor_numpy.shape)
print("\nDimension: \t",tensor_numpy.ndim)
print("\nRank: \t",tf.rank(tensor_numpy).numpy())
print("\nSize: \t",tf.size(tensor_numpy))

print("\n\nDataType of Elements: \t",tensor_numpy.dtype)
print("\nElement along axis 0: \t",tensor_numpy.shape[0])
print("\nElement along axis 1: \t",tensor_numpy.shape[1])
print("\nElement along axis 2: \t",tensor_numpy.shape[2])
print("\nTotal Number of Elements: \t",tf.size(tensor_numpy).numpy())

----Tensor Information----
Shape: 	 (2, 3, 4)

Dimension: 	 3

Rank: 	 3

Size: 	 tf.Tensor(24, shape=(), dtype=int32)


DataType of Elements: 	 <dtype: 'int16'>

Element along axis 0: 	 2

Element along axis 1: 	 3

Element along axis 2: 	 4

Total Number of Elements: 	 24


In [ ]:
# Working w Items of Each Dimension
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [ ]:
# First 2 Elements if Each Dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

**Arithmetic Operation with Tensors**


*   Add
*   Sub
*   Multi
*   Div

In [ ]:
tensor_one=tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [ ]:
# tensor_one+51
tf.add(tensor_one,51)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[62, 60],
       [53, 56]], dtype=int32)>

In [ ]:
tensor_one-5
tf.substract(tensor_one,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [ ]:
tensor_one*2
tf.multiply(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [ 4, 10]], dtype=int32)>

In [ ]:
tf.divide(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [ ]:
second_matrix=tf.constant([[8,16],[64,8.25],
                           [625,9.23],
                           [125,2.34],
                           [169,144]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[  8.    16.  ]
 [ 64.     8.25]
 [625.     9.23]
 [125.     2.34]
 [169.   144.  ]], shape=(5, 2), dtype=float32)


In [ ]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.8722813],
       [25.       ,  3.0380914],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

**Exercise**


*   Create two tensors with random values between 0 and 1, shape is [6,300].
*   Find out the following details: Number of elements (Size, Rank Shape)



In [3]:
import tensorflow as tf
import numpy as np

In [4]:
tensor1 = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)
tensor2 = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)

In [6]:
print("Tensor 1:",tensor1)
print("Shape:", tensor1.shape)
print("Rank (number of dimensions):", tf.rank(tensor1).numpy())
print("Size (number of elements):", tf.size(tensor1).numpy())

print("\nTensor 2:",tensor2)
print("Shape:", tensor2.shape)
print("Rank (number of dimensions):", tf.rank(tensor2).numpy())
print("Size (number of elements):", tf.size(tensor2).numpy())

Tensor 1: tf.Tensor(
[[0.38096333 0.57321274 0.3308916  ... 0.03738046 0.15039158 0.5510154 ]
 [0.4838134  0.14898992 0.6963273  ... 0.411157   0.29916465 0.95206106]
 [0.92234826 0.5095848  0.22799063 ... 0.82700753 0.24349892 0.91255736]
 [0.04476428 0.91807795 0.39316344 ... 0.90281403 0.9838128  0.43910694]
 [0.7918638  0.80026364 0.82623184 ... 0.8526491  0.36120427 0.1114161 ]
 [0.9994348  0.46961117 0.6084776  ... 0.8225057  0.46516848 0.7685852 ]], shape=(6, 300), dtype=float32)
Shape: (6, 300)
Rank (number of dimensions): 2
Size (number of elements): 1800

Tensor 2: tf.Tensor(
[[0.98611    0.58970356 0.20072412 ... 0.8971484  0.39366138 0.02520251]
 [0.96830904 0.5225736  0.64241624 ... 0.99501646 0.3673513  0.3597144 ]
 [0.05056632 0.74635315 0.3130474  ... 0.37805462 0.25078428 0.48841596]
 [0.1780076  0.844288   0.00273681 ... 0.6085745  0.71546066 0.8421842 ]
 [0.7237426  0.2985443  0.12554705 ... 0.5113636  0.5436231  0.5372293 ]
 [0.40581942 0.5283245  0.08485675 ... 0.2