## Numpy Introduction and  Usage

## 1. One Dimensional Array (1-D)

In [1]:
import numpy as np

In [2]:
array1=np.array([10,20,30,40,50])

In [3]:
print(array1)

[10 20 30 40 50]


## 2. Two Dimensional Array (2-D)

In [4]:
array_two=np.array([[10,20,30],[40,50,60]])

In [5]:
print(array_two)

[[10 20 30]
 [40 50 60]]


## 3. Three Dimensional Array (3-D Array)

In [6]:
array_three=np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,70]]])

In [7]:
print(array_three)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 70]]]


## Find Out Dimension of NumPy Array

In [8]:
print('First Array Dimension: \t ',array1.ndim)

First Array Dimension: 	  1


In [9]:
print('Second Array Dimension: \t ',array_two.ndim)

Second Array Dimension: 	  2


In [10]:
print('Third Array Dimension: \t ',array_three.ndim)

Third Array Dimension: 	  3


## Write An Array of 5 Students Marks using Numpy
   ### Marks: 80,70,75,99,89

In [11]:
marks=np.array([80,70,75,99,89])

In [13]:
print('Array of Marks: \t ',marks)

Array of Marks: 	  [80 70 75 99 89]


In [14]:
print(marks)

[80 70 75 99 89]


## Write an Array to take Marks of 5 Students in 3 Subjects using NumPy
### Maths, English, Chemistry
#### [[50,45,49],[40,42,45],[35,40,46],[39,40,45][48,40,40]]

In [18]:
marks_subject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])
print('2 D Array Example')
print(marks_subject)

2 D Array Example
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


## Write an Array: Take Marks of 4 Students in 3 Subjects for Two Semester using Numpy
    ### Maths, English, Chemistry
    #### Students Name: Dd, Irfan, Damian, Max
    #### Two Semester : Sem1, Sem2
        #### 4*3*2
        #### [[[85,88],[78,82],[90,95]], [[76,70],[40,45],[90,95]], [[80,86],[78,82],[90,95]], [[85,88],[78,82],[70,90]]

In [20]:
marks_subject_sem=np.array([
    [[85,88],[78,82],[90,95]], 
    [[76,70],[40,45],[90,95]], 
    [[80,86],[78,82],[90,95]], 
    [[85,88],[78,82],[70,90]]
                           ])

In [22]:
print(marks_subject_sem)

[[[85 88]
  [78 82]
  [90 95]]

 [[76 70]
  [40 45]
  [90 95]]

 [[80 86]
  [78 82]
  [90 95]]

 [[85 88]
  [78 82]
  [70 90]]]


## Write an Array: Take Weather of 2 Cities in 3 Days for Three Times in a Day; Morning, Noon, Evening
#### Cities Names: Kuala Lumpur, Edinburgh
#### Saturday, Sunday, Monday
#### Three Time Slot: Morning, Noon, Evening
### Create 3-D Array for this Using Numpy and Print it

In [24]:
weather=np.array([[
    [25,33,27], 
    [26,32,30],
    [26,31,25]],
                 [
    [12,15,18],
    [11,18,13],
    [12,14,18]]])

In [25]:
print('Datas Weather (C): \t ')
print(weather)

Datas Weather (C): 	 
[[[25 33 27]
  [26 32 30]
  [26 31 25]]

 [[12 15 18]
  [11 18 13]
  [12 14 18]]]


In [26]:
cities=["Kuala Lumpur", "Edinburgh"]
days=["Saturday", "Sunday", "Monday"]
times=["Morning", "Noon", "Evening"]

In [27]:
print("\nDetailed Weather Data:")
for i, city in enumerate(cities):
    print(f"\nCity: {city}")
    for j, day in enumerate(days):
        print(f"  {day}: Morning={weather[i][j][0]}°C, Noon={weather[i][j][1]}°C, Evening={weather[i][j][2]}°C")


Detailed Weather Data:

City: Kuala Lumpur
  Saturday: Morning=25°C, Noon=33°C, Evening=27°C
  Sunday: Morning=26°C, Noon=32°C, Evening=30°C
  Monday: Morning=26°C, Noon=31°C, Evening=25°C

City: Edinburgh
  Saturday: Morning=12°C, Noon=15°C, Evening=18°C
  Sunday: Morning=11°C, Noon=18°C, Evening=13°C
  Monday: Morning=12°C, Noon=14°C, Evening=18°C


In [28]:
print(array1)

[10 20 30 40 50]


In [29]:
print('Shape of Array1: \t ',array1.shape)

Shape of Array1: 	  (5,)


In [30]:
print('Size of Array1: \t ',array1.size)

Size of Array1: 	  5


In [31]:
print('Data Type: \t ',array1.dtype)

Data Type: 	  int64


In [32]:
students=np.array(['Dd','Irfan','Joe','Maxton'])

In [33]:
print(students)

['Dd' 'Irfan' 'Joe' 'Maxton']


In [34]:
print('Shape of Array: \t ',students.shape)

Shape of Array: 	  (4,)


In [35]:
print('Numbers of Students: \t ',students.size)

Numbers of Students: 	  4


In [36]:
print('Data Type: \t ',students.dtype)

Data Type: 	  <U6


## Mathematical Operations

In [37]:
print(array1)

[10 20 30 40 50]


In [38]:
total=sum(array1)

In [39]:
print(total)

150


In [40]:
print('Mean: \t ',np.mean(array1))

Mean: 	  30.0


In [41]:
print('Min: \t ',np.min(array1))

Min: 	  10


In [42]:
print('Max: \t ',np.max(array1))

Max: 	  50


In [43]:
print('Index of Min: \t ',np.argmin(array1))

Index of Min: 	  0


In [45]:
print('Index of Max: \t ',np.argmax(array1))

Index of Max: 	  4


In [46]:
our_arr=np.array([100,200,300,7000,400,500,300,1900,600])

In [47]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


### Searching and Sorting Example in 1-Day Array

In [54]:
sorted_array=np.sort(our_arr)
print('***Sorted Array***')
print(sorted_array)

***Sorted Array***
[ 100  200  300  300  400  500  600 1900 7000]


In [55]:
print('Is there any item > 500?: \t ',np.any(sorted_array>500))

Is there any item > 500?: 	  True


In [56]:
print('All > 99 ?: \t ',np.all(sorted_array>99))

All > 99 ?: 	  True


In [57]:
print('All > 500 ?: \t ',np.all(sorted_array>500))

All > 500 ?: 	  False


In [58]:
print('Where Values > 500 ?: \t ',np.where(sorted_array>500))

Where Values > 500 ?: 	  (array([6, 7, 8]),)


In [59]:
print('All Numbers > 500: \t ')
for num in np.where(sorted_array>500):
    print(num)

All Numbers > 500: 	 
[6 7 8]


In [61]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


In [62]:
print(min(our_arr))

100


In [65]:
print('Index of Min: \t ',np.argmin(our_arr))

Index of Min: 	  0


In [66]:
print('Index of Max: \t ',np.argmax(our_arr))

Index of Max: 	  3


In [68]:
print('All Numbers > 500: \t ')
for num in sorted_array>500:
    print(num)

All Numbers > 500: 	 
False
False
False
False
False
False
True
True
True


In [70]:
selected_values=sorted_array[sorted_array>500]

In [71]:
print(selected_values)

[ 600 1900 7000]


In [72]:
for num in selected_values:
    print(num)

600
1900
7000


## Slicing (1-D) Array
   1. To take Elements from Starting Index to End Index
   2. e.g. [started:end] 

In [77]:
print(sorted_array)

[ 100  200  300  300  400  500  600 1900 7000]


In [79]:
slice_sorted_array=sorted_array[1:3]
print(slice_sorted_array)

[200 300]


### Starting from An Index and Going till Last

In [80]:
print(sorted_array[3:])

[ 300  400  500  600 1900 7000]


In [83]:
print(sorted_array[:4])

[100 200 300 300]


In [82]:
print(sorted_array[:5])

[100 200 300 300 400]


### Step
    ### [start:end:step]
    ### step: every step element

In [84]:
our_slice=sorted_array[1:6:2]
print(our_slice)

[200 300 500]


In [86]:
print('Original Array')
print(sorted_array)
print()
print('Every Third Element')
every_third_element=sorted_array[::3]
print(every_third_element)

Original Array
[ 100  200  300  300  400  500  600 1900 7000]

Every Third Element
[100 300 600]


### Slice Reverse

In [87]:
print('Original Array')
print(sorted_array)
print()
print('Revers Array: \t ',sorted_array[::-1])

Original Array
[ 100  200  300  300  400  500  600 1900 7000]

Revers Array: 	  [7000 1900  600  500  400  300  300  200  100]


In [88]:
print('Last 5 Elements')
print(sorted_array[::-5])

Last 5 Elements
[7000  300]
