In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('students.xlsx')
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


In [6]:
marks=df['Marks'].to_numpy()
print('NumPy Array of Marks: \t ')
print(marks)

NumPy Array of Marks: 	 
[85 90 78 92 90 45]


In [8]:
print('Highest Marks: \t ',np.max(marks))

Highest Marks: 	  92


In [9]:
print('Lowest Marks: \t ',np.min(marks))

Lowest Marks: 	  45


In [10]:
print('Average Marks: \t ',np.mean(marks))

Average Marks: 	  80.0


### .loc: Label Based
### .iloc: Index Based

In [12]:
print('Original Dataframe: \t ')
print(df)
print()
print('Location: Label Based')
print(df.loc[2])

Original Dataframe: 	 
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45

Location: Label Based
Name     Bob
Age       21
Marks     78
Name: 2, dtype: object


In [13]:
print('Original Dataframe: \t ')
print(df)
print()
print('Location: Label Based')
print(df.loc[4])

Original Dataframe: 	 
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45

Location: Label Based
Name     Sam
Age       25
Marks     90
Name: 4, dtype: object


In [14]:
print('Original Dataframe: \t ')
print(df)
print()
print('Location: Label Based')
print(df.loc[0])

Original Dataframe: 	 
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45

Location: Label Based
Name     John
Age        20
Marks      85
Name: 0, dtype: object


In [15]:
print('Original Dataframe: \t ')
print(df)
print()
print('Location: Label Based')
print(df.loc[4],['Name'])

Original Dataframe: 	 
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45

Location: Label Based
Name     Sam
Age       25
Marks     90
Name: 4, dtype: object ['Name']


In [16]:
print('Original Dataframe: \t ')
print(df)
print()
print('Location: Label Based')
print(df.loc[4,['Name','Marks']])

Original Dataframe: 	 
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45

Location: Label Based
Name     Sam
Marks     90
Name: 4, dtype: object


In [18]:
print('Original Dataframe: \t ')
print(df)
print()
print('Location: Index Based')
print(df.iloc[2,[1,2]])

Original Dataframe: 	 
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45

Location: Index Based
Age      21
Marks    78
Name: 2, dtype: object


### Axis in NumPy:
   1. Axis 0: Vertical Direction; Works Column-Wise
   2. Axis 1: Horizontal Direction; Works Row-Wise

### Two Students Marks in 3 Subjects
    [[45,50,49],[30,45,49]]

In [19]:
marks_arr=np.array([[5,2,9],[10,40,60]])
print(marks_arr)

[[ 5  2  9]
 [10 40 60]]


In [20]:
print('Sum Down Each Column: \t ',np.sum(marks_arr,axis=0))

Sum Down Each Column: 	  [15 42 69]


In [21]:
print('Sum Down Each Row',np.sum(marks_arr,axis=1))

Sum Down Each Row [ 16 110]


In [24]:
print('NumPy Array of Marks: \t ')
print()
print(marks)

NumPy Array of Marks: 	 

[85 90 78 92 90 45]


In [25]:
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


#### Find The Student Name Who Got Highest Marks

In [26]:
topper=df.loc[df['Marks'].idxmax(),'Name']
print(topper)

Sara


In [27]:
lastinclass=df.loc[df['Marks'].idxmin(),'Name']
print(lastinclass)

Rohit


In [28]:
print('Next Example: \t ')

Next Example: 	 


In [29]:
top_index=df['Marks'].idxmax()
top_students=df.iloc[top_index,df.columns.get_loc('Name')]
print('Topper of The Class is: \t ',top_students)

Topper of The Class is: 	  Sara
